version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/urscene

hooks:
  ApplicationStop:
    - location: script/stop.sh
      runas: root
  AfterInstall:
    - location: script/initialize.sh
      runas: root
  ApplicationStart:
    - location: script/start.sh
      runas: root
